=== becto-fli4l/fli4l-60808-orig/src/_TOOLS/xml/rrd-graph.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
   <xs:annotation>
      <xs:appinfo>rrd-graph</xs:appinfo>
      <xs:documentation>
         RRD-graph XML file
      </xs:documentation>
   </xs:annotation>
   <xs:element name="rrd-graph" type="rrd-graphT"/>
   <xs:complexType name="rrd-graphT">
      <xs:annotation>
         <xs:documentation>
            RRD-graph file root element.<br/>
            Must contain one &lt;rrd&gt; element
            and one or multiple &lt;graph&gt; element.
         </xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="header" type="headerT"/>
         <xs:element name="rrd" type="rrdT" minOccurs="0"/>
         <xs:element name="hwmon" type="hwmonT" minOccurs="0"/>
         <xs:element name="cat" type="catT" minOccurs="0"/>
         <xs:element name="graph" type="graphT" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element name="include" type="includeT" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="headerT">
      <xs:annotation>
         <xs:documentation>
            Header definitions.
         </xs:documentation>
      </xs:annotation>      
      <xs:attribute name="name" use="required" type="xs:NCName">
         <xs:annotation>
            <xs:documentation>
               Name prefix.<br/>
               The graph functions are named "[header/@name]_[graph/@name]_graph ()".
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="title" use="required" type="labelT">
         <xs:annotation>
            <xs:documentation>
               Title prefix of the RRD graphs.<br/>
               This text will be prefixed to the title displayed in the RRD graph.<br/>
               This text can be a variable name in the .cgi's language file.
               In this case it has to be written as title="${&lt;varname&gt;}"
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:complexType name="rrdT">
      <xs:annotation>
         <xs:documentation>
            RRD Database definitions.
         </xs:documentation>
      </xs:annotation>
      <xs:attribute name="db" use="optional" type="xs:string">
         <xs:annotation>
            <xs:documentation>
               Name of the RRD database (=rrd/@db)<br/>
               The complete access path to an rrd variable is<br/>
               "/data/rrdtool/db/[machine-name];/[rrd/@db]/[var/@rrd]:value".
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="exponent" use="optional" type="xs:integer">
         <xs:annotation>
            <xs:documentation>
               The units exponent.<br/>
               Force the units exponent, e.g. 3 for kilo(10e3) or 6 for Mega(10e6).
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:complexType name="hwmonT">
      <xs:annotation>
         <xs:documentation>
            Hwmon sensor definitions
         </xs:documentation>
      </xs:annotation>
      <xs:attribute name="chip" use="required" type="xs:NCName">
         <xs:annotation>
            <xs:documentation>
               Sensor chip.<br/>
               Sensor  chip for hwmon variables" 
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:complexType name="catT">
      <xs:annotation>
         <xs:documentation>
            
         </xs:documentation>
      </xs:annotation>
      <xs:attribute name="path" use="required" type="xs:anyURI">
         <xs:annotation>
            <xs:documentation>
               
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:complexType  name="graphT">
      <xs:annotation>
         <xs:documentation>
            RRD graph element.<br/>
            Each file must have one ore multiple &lt;graph&gt; elements.<br/>
            Eech &lt;graph&gt; element results in an graph function. 
         </xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="rrd" type="rrdT" minOccurs="0"/>
         <xs:element name="hwmon" type="hwmonT" minOccurs="0"/>
         <xs:element name="cat" type="catT" minOccurs="0"/>
         <xs:element maxOccurs="unbounded" name="group" type="groupT"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NCName">
         <xs:annotation>
            <xs:documentation>
               Name of the graph function.<br/>
               The graph functions are named "[header/@name]_[graph/@name]_graph ()".
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="tab" use="optional" type="labelT">
         <xs:annotation>
            <xs:documentation>
               Tab title of the RRD graphs.<br/>
               This text should be a variable name in the .cgi's language file.
               In this case it has to be written as title="${&lt;varname&gt;}"
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="title" use="required" type="labelT">
         <xs:annotation>
            <xs:documentation>
               Title of the RRD graphs.<br/>
               This text will be prefixed by the title defined in [header/@title].
               This text should be a variable name in the .cgi's language file.
               In this case it has to be written as title="${&lt;varname&gt;}"
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="label" use="required" type="labelT">
         <xs:annotation>
            <xs:documentation>
               Vertical label<br/>
               This text should be a variable name in the .cgi's language file.
               In this case it has to be written as title="${&lt;varname&gt;}"
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="minmax" use="optional" default="true" type="xs:boolean">
         <xs:annotation>
            <xs:documentation>
               Show maximum, average and minimum in caption.<br/>
               When this attribute is "false", no maximum, avarage and minimum columns will
               be displayed in the caption area.<br/>
               This attribute defaults to "true" if not entered.
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="area" use="optional" default="false" type="xs:boolean">
         <xs:annotation>
            <xs:documentation>
               Show all variables as areas.<br/>
               When this attribute is "true", the variables are renedered as 
               AREA's instead of LINE's.<br/>
               When the attribute stack is "true" all areas will be stacked in
               the order of the &lt;var&gt;> elements in the file.<br/>
               When the attribute stack is "false" the areas will overwrite in 
               the order of the &lt;var&gt;> elements in the file. A line is written
               rendered for each &lt;var&gt; element after the areas.<br/>
               This attribute defaults to "false" if not entered".
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="stack" use="optional" default="false" type="xs:boolean">
         <xs:annotation>
            <xs:documentation>
               Stack the variables areas.<br/>
               When the attribute stack is "true" all areas will be stacked in
               the order of the &lt;var&gt;> elements in the file.<br/>
               When the attribute area is "false", the attribute stack has no effect.<br/>
               This attribute defaults to "false" if not entered.
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:complexType name="includeT">
      <xs:annotation>
         <xs:documentation>
            Inluded tab entry.
         </xs:documentation>
      </xs:annotation>
      <xs:attribute name="name" use="required" type="xs:NCName">
         <xs:annotation>
            <xs:documentation>
               Name of the included function.<br/>
               The included functions are named "[header/@name]_[include/@name] ()".
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="tab" use="required" type="labelT">
         <xs:annotation>
            <xs:documentation>
               Tab title of the etxra entry.<br/>
               This text should be a variable name in the .cgi's language file.
               In this case it has to be written as title="${&lt;varname&gt;}"
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="include" use="required" type="xs:anyURI">
         <xs:annotation>
            <xs:documentation>
               Include file name.<br/>
               Normaly /srv/www/include/&lt;file&gt;.inc. 
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="func" use="required" type="xs:NCName">
         <xs:annotation>
            <xs:documentation>
               Name of the extra function.
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="condition" use="optional" type="xs:string">
         <xs:annotation>
            <xs:documentation>
               Condition when include is active
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:complexType name="groupT">
      <xs:annotation>
         <xs:documentation>
            Group of RRD variables.<br/>
            Each graph must have one multiple variable groups, each group containing
            one or multiple variables.<br/>
            Having multiple groups can be used to display optional rrd-variables, eg.
            when a variable is not written in every case.<br/>
            When having multiple groups, the group containing the maximum amount of 
            variables must be the first in order. All following groups must be subsets of
            the preceeding groups.
         </xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element maxOccurs="unbounded" name="var" type="varT"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="varT">
      <xs:annotation>
         <xs:documentation>
            RRD variable.<br/>
            Defines a LINE or AREA for displaying a RRD data value.
            Each variable can be scaled before displaying.
         </xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="rrd" type="rrdT" minOccurs="0"/>
         <xs:element name="hwmon" type="hwmonT" minOccurs="0"/>
         <xs:element name="cat" type="catT" minOccurs="0"/>
         <xs:element minOccurs="0" maxOccurs="unbounded" name="cat-scale" type="scale-intT">
            <xs:annotation>
               <xs:documentation>
                  Scale the cat data values.<br/>
                  Apply the scaling operations to the cat data values when displayed.
                  Multiple scaling operations are aplied in order of apearance.<br/>
                  E.g. &lt;cat-scale val="2" op="*"&gt; will multiply the value by 2.
               </xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element minOccurs="0" maxOccurs="unbounded" name="scale" type="scale-floatT">
            <xs:annotation>
               <xs:documentation>
                  Scale the RRD data values.<br/>
                  Apply the scaling operations to the RRD data values when displayed as 
                  graph and in caption.
                  Multiple scaling operations are aplied in order of apearance.<br/>
                  E.g. &lt;scale val="2" op="*"&gt; will multiply every value by 2.
               </xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element minOccurs="0" maxOccurs="unbounded" name="disp-scale" type="scale-floatT">
            <xs:annotation>
               <xs:documentation>
                  Scale the RRD data values in display.<br/>
                  Apply the scaling operations to the RRD data values when 
                  displaying as graph only. This scaling operation is applied after 
                  the operations defined by &lt;scale&gt; elements. 
                  Multiple scaling operations are aplied in order of apearance
               </xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
      <!-- caption label, should be translatable 
           use ${_MYCGI_TEXT_REPLACEMENT} -->
      <xs:attribute name="label" use="required" type="labelT">
         <xs:annotation>
            <xs:documentation>
               Variable label.<br/>
               This text will be displayed in the caption area.<br/>
               This text should be a variable name in the .cgi's language file.
               In this case it has to be written as label="${&lt;varname&gt;}"
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <!-- rrd database variable, reflects .rrd file -->
      <xs:attribute name="rrd" use="required" type="xs:NCName">
         <xs:annotation>
            <xs:documentation>
               Name of the RRD variable<br/>
               The complete access path to an rrd variable is<br/>
               "/data/rrdtool/db/[machine-name];/[rrd/@db]/[var/@rrd]:value".
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="sensor" use="optional" type="sensorT">
         <xs:annotation>
            <xs:documentation>
               Name of the sensor variable.
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="cat" use="optional" type="xs:anyURI"/>
      <!-- rrd variable name (overrides 'value') -->
      <xs:attribute name="val" use="optional" type="xs:NCName">
         <xs:annotation>
            <xs:documentation>
               RRD date value name.<br/>
               This attribute overides the dfault value "value" used in the 
               rrd access path.<br/>
               The complete access path to an rrd variable is<br/>
               "/data/rrdtool/db/[machine-name];/[rrd/@db]/[var/@rrd]:[var/@val]".
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="color" use="required" type="colorT">
         <xs:annotation>
            <xs:documentation>
               Color of the graph.<br/>
               Must be entered as HTML color in the format "#RRGGBB", with 
               RR GG and BB be hexadecimal values from 00 to FF.
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <!-- format string for max,avg,min,last value e.g. "%.1lf" -->
      <xs:attribute name="format" use="required" type="xs:string">
         <xs:annotation>
            <xs:documentation>
               Format string.<br/>
               Format for the maximum, average, minumum and last values displayed 
               in the caption area.<br/>
               The format has to be entered as printf format string, 
               eg. "%.1lf" for double values with precision 1.
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="dashes" use="optional" type="dashesT">
         <xs:annotation>
            <xs:documentation>
               Render dashed line.<br/>
               When this attribute is set a dashed line will be rendered with pixel widths as entered.
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:complexType name="scale-floatT">
      <xs:attribute name="val" use="required" type="xs:double">
         <xs:annotation>
            <xs:documentation>
               Scaling value.<br/>
               Value to be applied by the scaling operation define in scale/@op.
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="op" use="required" type="op_T"/>
   </xs:complexType>
   <xs:complexType name="scale-intT">
      <xs:attribute name="val" use="required" type="xs:integer">
         <xs:annotation>
            <xs:documentation>
               Scaling value.<br/>
               Value to be applied by the scaling operation define in scale/@op.
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="op" use="required" type="op_T"/>
   </xs:complexType>
   <xs:simpleType name="colorT">
      <xs:restriction base="xs:string">
         <xs:pattern value="#[0-9a-fA-F]{6}"/>
      </xs:restriction>
   </xs:simpleType>   
   <xs:simpleType name="op_T">
      <xs:annotation>
         <xs:documentation>
            Scaling operation.<br/>
            The operation applied to the scaling factor. Must be one of<br/>
            "*" mulitplication<br/>
            "/" division<br/>
            "+" addition<br/>
            "-" substraction.<br/>
         </xs:documentation>
      </xs:annotation>
      <xs:restriction base="xs:string">
         <xs:pattern value="[+-/*]{1}"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="dashesT">
      <xs:restriction base="xs:string">
         <xs:pattern value="[1-9]([0-9])*(,[1-9]([0-9])*(,[1-9]([0-9])*,[1-9]([0-9])*)*)?"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="sensorT">
      <xs:restriction base="xs:string">
         <xs:pattern value="(in|temp|fan)[0-9]*"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="labelT">
      <xs:restriction base="xs:string">
         <xs:pattern value="(([-+&amp;_/ a-zA-Z0-9]*)|($\{_[_A-Z0-9]*\}))*"/>
      </xs:restriction>
   </xs:simpleType>
</xs:schema>

=== becto-fli4l/fli4l-60808-orig/src/packages/rrdtool/opt/srv/www/include/rrd-status_apcups.xml
<?xml version="1.0" encoding="UTF-8"?>
<rrd-graph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="../../../../../../../_TOOLS/xml/rrd-graph.xsd">
   <rrd name="apcups" db="apcups" title="APC-UPS"/>
   <graph name="charge" title="${_RRD3_RT_CHARGE}" label="${_RRD3_RL_CHARGE}">
      <group>
         <var label="${_RRD3_RC_BATTERY}" rrd="charge" color="#009900" format="%.1lf"/>
      </group>
   </graph>
   <graph name="frequency" title="${_RRD3_RT_FREQUENCY}" label="${_RRD3_RL_FREQUENCY}">
      <group>
         <var label="${_RRD3_RC_INPUT}" rrd="frequency-input" val="frequency" color="#009900" format="%.2lf"/>
      </group>
   </graph>
   <graph name="load" title="${_RRD3_RT_LOAD}" label="${_RRD3_RL_LOAD}">
      <group>
         <var label="${_RRD3_RC_OUTPUT}" rrd="percent-load" val="percent" color="#FF0000" format="%.1lf"/>
      </group>
   </graph>
   <graph name="temperature" title="${_RRD3_RT_TEMPERATUE}" label="${_RRD3_RL_TEMPERATUE}">
      <group>
         <var label="${_RRD3_RC_INTERNAL}" rrd="temperature" color="#009900" format="%.1lf"/>
      </group>
   </graph>
   <graph name="timeleft" title="${_RRD3_RT_TIMELEFT}" label="${_RRD3_RL_TIMELEFT}">
      <group>
         <var label="${_RRD3_RC_BATTERY}" rrd="timeleft" val="timeleft" color="#009900" format="%.1lf"/>
      </group>
   </graph>
   <graph name="batvolt" title="${_RRD3_RT_BATVOLT}" label="${_RRD3_RL_VOLT}">
      <group>
         <var label="${_RRD3_RC_BATTERY}" rrd="voltage-battery" color="#009900" format="%.2lf"/>
      </group>
   </graph>
   <graph name="pwrvolt" title="${_RRD3_RT_PWRVOLT}" label="${_RRD3_RL_VOLT}">
      <group>
         <var label="${_RRD3_RC_INPUT}" rrd="voltage-input" color="#009900" format="%.1lf"/>
         <var label="${_RRD3_RC_OUTPUT}" rrd="voltage-output" color="#FF0000" format="%.1lf">
            <disp-scale val="0.2" op="+"/>
         </var>
      </group>
   </graph>
</rrd-graph>

=== becto-fli4l/fli4l-60808-orig/src/packages/hwsupp/opt/srv/www/xml/winnet-pc640.xml
<?xml version="1.0" encoding="UTF-8"?>
<rrd-graph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="../../../../../../../_TOOLS/xml/rrd-graph.xsd">
   <header name="winnet_pc640" title="WinNet PC640"/>
   <rrd db="sensors-w83697hf-isa-0290"/>
   <hwmon chip="w83697hf-isa-0290"/>
   <graph name="temp" tab="${_HWSUPP_TEMP}" title="${_HWSUPP_RT_TEMP}" label="${_HWSUPP_RL_TEMP}">
      <group>
         <var label="${_HWSUPP_RC_CPU}" rrd="temperature-temp2" sensor="temp2" color="#FF0000" format="%.1lf"/>
         <var label="${_HWSUPP_RC_MB}" rrd="temperature-temp1" sensor="temp1" color="#0000FF" format="%.1lf"/>
      </group>
   </graph>
   <graph name="voltage" tab="${_HWSUPP_VOLTAGE}" title="${_HWSUPP_RT_VOLTAGE}" label="${_HWSUPP_RL_VOLTAGE}">
      <group>
         <var label="${_HWSUPP_RC_VCORE}" rrd="voltage-in0" sensor="in0" color="#FF0000" format="%.2lf"/>
         <var label="${_HWSUPP_RC_V3_3}" rrd="voltage-in2" sensor="in2" color="#FFFF00" format="%.2lf"/>
         <var label="${_HWSUPP_RC_V5}" rrd="voltage-in3" sensor="in3" color="#00FF00" format="%.2lf"/>
         <var label="${_HWSUPP_RC_V12}" rrd="voltage-in4" sensor="in4" color="#0000FF" format="%.2lf"/>
         <var label="${_HWSUPP_RC_V5SB}" rrd="voltage-in7" sensor="in7" color="#990000" format="%.2lf"/>
      </group>
   </graph>
   <include name="hwmon" tab="${_HWSUPP_HWMON}" include="hwmon-winnet-pc640.inc" func="hwmon_winnet_pc640"/>
   <include name="bios" tab="${_HWSUPP_DMI}" include="extra-dmidecode.inc" func="extra_dmidecode"/>
</rrd-graph>

=== becto-fli4l/fli4l-60808-orig/src/packages/hwsupp/opt/srv/www/xml/pcengines-apu.xml
<?xml version="1.0" encoding="UTF-8"?>
<rrd-graph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="../../../../../../../_TOOLS/xml/rrd-graph.xsd">
   <header name="pcengines_apu" title="PC Engines APU"/>
   <rrd db="sensors-k10temp-pci-00c3"/>
   <hwmon chip="k10temp-pci-00c3"/>
   <graph name="temp" tab="${_HWSUPP_TEMP}" title="${_HWSUPP_RT_TEMP}" label="${_HWSUPP_RL_TEMP}">
      <group>
         <var label="${_HWSUPP_RC_CPU}" rrd="temperature-temp1" sensor="temp1" color="#FF0000" format="%.1lf"/>
      </group>
   </graph>
   <graph name="frequency" tab="${_HWSUPP_FREQUENCY}" title="${_HWSUPP_RT_FREQUENCY}" label="${_HWSUPP_RL_FREQUENCY}">
      <rrd db="cpufreq" exponent="0"/>
      <cat path="/sys/devices/system/cpu"/>
      <group>
         <var label="${_HWSUPP_RC_CPU} 0" rrd="cpufreq-0" cat="cpu0/cpufreq/cpuinfo_cur_freq" color="#FF0000" format="%.1lf">
            <cat-scale val="1000" op="/"/>
            <scale val="1000000" op="/"/>
         </var>
         <var label="${_HWSUPP_RC_CPU} 1" rrd="cpufreq-1" cat="cpu1/cpufreq/cpuinfo_cur_freq" color="#00FF00" format="%.1lf">
            <cat-scale val="1000" op="/"/>
            <scale val="1000000" op="/"/>
         </var>
      </group>
   </graph>
   <include name="hwmon" tab="${_HWSUPP_HWMON}" include="hwmon-pcengines-apu.inc" func="hwmon_pcengines_apu"/>
   <include name="cpufreq" tab="${_HWSUPP_CPUFREQ}" include="extra-cpufreq.inc" func="extra_cpufreq" condition="$hwsupp_cpufreq"/>
   <include name="bios" tab="${_HWSUPP_DMI}" include="extra-dmidecode.inc" func="extra_dmidecode"/>
</rrd-graph>

=== becto-fli4l/fli4l-60808-orig/src/packages/hwsupp/opt/srv/www/xml/lex-cv860a.xml
<?xml version="1.0" encoding="UTF-8"?>
<rrd-graph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="../../../../../../../_TOOLS/xml/rrd-graph.xsd">
   <header name="lex_cv860a" title="LEX Computech CV860A"/>
   <rrd db="sensors-via686a-isa-6000"/>
   <hwmon chip="via686a-isa-6000"/>
   <graph name="temp" tab="${_HWSUPP_TEMP}" title="${_HWSUPP_RT_TEMP}" label="${_HWSUPP_RL_TEMP}">
      <group>
         <var label="${_HWSUPP_RC_CPU}" rrd="temperature-temp2" sensor="temp2"  color="#FF0000" format="%.1lf"/>
         <var label="${_HWSUPP_RC_MB}" rrd="temperature-temp1" sensor="temp1" color="#0000FF" format="%.1lf"/>
      </group>
   </graph>
   <graph name="voltage" tab="${_HWSUPP_VOLTAGE}" title="${_HWSUPP_RT_VOLTAGE}" label="${_HWSUPP_RL_VOLTAGE}">
      <group>
         <var label="${_HWSUPP_RC_VCORE}" rrd="voltage-in0" sensor="in0" color="#FF0000" format="%.2lf"/>
         <var label="${_HWSUPP_RC_V2_5}" rrd="voltage-in1" sensor="in1" color="#FFFF00" format="%.2lf"/>
         <var label="${_HWSUPP_RC_VIO}" rrd="voltage-in2" sensor="in2" color="#00FF00" format="%.2lf"/>
         <var label="${_HWSUPP_RC_V5}" rrd="voltage-in3" sensor="in3" color="#0000FF" format="%.2lf"/>
         <var label="${_HWSUPP_RC_V12}" rrd="voltage-in4" sensor="in4" color="#FF00FF" format="%.2lf"/>
      </group>
   </graph>
   <graph name="frequency" tab="${_HWSUPP_FREQUENCY}"  title="${_HWSUPP_RT_FREQUENCY}" label="${_HWSUPP_RL_FREQUENCY}">
      <rrd db="cpufreq"/>
      <cat path="/sys/devices/system/cpu"/>
      <group>
         <var label="${_HWSUPP_RC_CPU}" rrd="cpufreq-0" cat="cpu0/cpufreq/cpuinfo_cur_freq" color="#FF0000" format="%.1lf">
            <cat-scale val="1000" op="/"/>
            <scale val="1000000" op="/"/>
         </var>
      </group>
   </graph>
   <include name="hwmon" tab="${_HWSUPP_HWMON}" include="hwmon-lex-cv860a.inc" func="hwmon_lex_cv860a"/>
   <include name="cpufreq" tab="${_HWSUPP_CPUFREQ}" include="extra-cpufreq.inc" func="extra_cpufreq" condition="$hwsupp_cpufreq"/>
   <include name="bios" tab="${_HWSUPP_DMI}" include="extra-dmidecode.inc" func="extra_dmidecode"/>
</rrd-graph>

=== becto-fli4l/fli4l-60808-orig/src/packages/hwsupp/opt/srv/www/xml/msi-ms-9803.xml
<?xml version="1.0" encoding="UTF-8"?>
<rrd-graph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="../../../../../../../_TOOLS/xml/rrd-graph.xsd">
   <header name="msi_ms_9803" title="MSI MS-9803"/>
   <rrd db="none"/>
   <hwmon chip="none"/>
   <graph name="frequency" tab="${_HWSUPP_FREQUENCY}" title="${_HWSUPP_RT_FREQUENCY}" label="${_HWSUPP_RL_FREQUENCY}">
      <rrd db="cpufreq" exponent="0"/>
      <cat path="/sys/devices/system/cpu"/>
      <group>
         <var label="${_HWSUPP_RC_CPU} 0" rrd="cpufreq-0" cat="cpu0/cpufreq/cpuinfo_cur_freq" color="#FF0000" format="%.1lf">
            <cat-scale val="1000" op="/"/>
            <scale val="1000000" op="/"/>
         </var>
         <var label="${_HWSUPP_RC_CPU} 1" rrd="cpufreq-1" cat="cpu1/cpufreq/cpuinfo_cur_freq" color="#00FF00" format="%.1lf">
            <cat-scale val="1000" op="/"/>
            <scale val="1000000" op="/"/>
         </var>
         <var label="${_HWSUPP_RC_CPU} 2" rrd="cpufreq-2" cat="cpu2/cpufreq/cpuinfo_cur_freq" color="#0000FF" format="%.1lf">
            <cat-scale val="1000" op="/"/>
            <scale val="1000000" op="/"/>
         </var>
         <var label="${_HWSUPP_RC_CPU} 3" rrd="cpufreq-3" cat="cpu3/cpufreq/cpuinfo_cur_freq" color="#FFFF00" format="%.1lf">
            <cat-scale val="1000" op="/"/>
            <scale val="1000000" op="/"/>
         </var>
      </group>
      <group>
         <var label="${_HWSUPP_RC_CPU} 0" rrd="cpufreq-0" cat="cpu0/cpufreq/cpuinfo_cur_freq" color="#FF0000" format="%.1lf">
            <cat-scale val="1000" op="/"/>
            <scale val="1000000" op="/"/>
         </var>
         <var label="${_HWSUPP_RC_CPU} 1" rrd="cpufreq-1" cat="cpu1/cpufreq/cpuinfo_cur_freq" color="#00FF00" format="%.1lf">
            <cat-scale val="1000" op="/"/>
            <scale val="1000000" op="/"/>
         </var>
      </group>
      <group>
         <var label="${_HWSUPP_RC_CPU} 0" rrd="cpufreq-0" cat="cpu0/cpufreq/cpuinfo_cur_freq" color="#FF0000" format="%.1lf">
            <cat-scale val="1000" op="/"/>
            <scale val="1000000" op="/"/>
         </var>
      </group>
   </graph>
   <include name="hwmon" tab="${_HWSUPP_HWMON}" include="hwmon-msi-ms-9803.inc" func="hwmon_msi_ms_9803"/>
   <include name="cpufreq" tab="${_HWSUPP_CPUFREQ}" include="extra-cpufreq.inc" func="extra_cpufreq" condition="$hwsupp_cpufreq"/>
   <include name="bios" tab="${_HWSUPP_DMI}" include="extra-dmidecode.inc" func="extra_dmidecode"/>
</rrd-graph>
